export { HomePage } from './home'
export { AboutPage } from './about'
export { SolutionsPage } from './solutions'
export { ContactPage } from './contact'
export { PartnerPage } from './partner'
export { InvestorPage } from './investor'
export { NotFoundPage } from './not-found'
