export { HomePage } from './home'
export { AboutPage } from './about'
export { SolutionsPage } from './solutions'
export { ContactPage } from './contact'
export { ImpressumPage } from './impressum'
export { DatenschutzPage } from './datenschutz'
export { NotFoundPage } from './not-found'
